before_script:
  - bash .gitlab-ci-docker.sh > /dev/null

test:5.6:
  image: php:5.6
  script:
    - phpunit
    - bash <(curl -s https://codecov.io/bash) -t 3178ac1f-03f7-4ad3-938e-523340065d80

test:7.0:
  image: php:7.0
  script:
    - phpunit
    - bash <(curl -s https://codecov.io/bash) -t 3178ac1f-03f7-4ad3-938e-523340065d80
