sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true

before_script:
  - mkdir -p build/logs
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php bin/phpunit -c . --coverage-clover build/logs/clover.xml

after_script:
  - php bin/coveralls -vvv

notifications:
  email: martin.aarhof@gmail.com
