sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - php bin/phpunit --coverage-clover=clover.xml

after_script:
  - php bin/coveralls -vvv
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: martin.aarhof@gmail.com
