name: PHP Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-stan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4','5.6']
    steps:
     - name: Install PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php-versions }}
         ini-values: "post_max_size=256M" #optional

     - uses: actions/checkout@v2
       with:
         path: api-php

     - name: Install composer and run PhpStan
       run: |
         composer install
         vendor/phpstan/phpstan/phpstan analyze .
       working-directory: api-php

     - name: Run PHP-CS-Fixer
       run: |
         vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix . --dry-run
       working-directory: api-php

     - name: Run Linter for PHP
       run: |
         vendor/overtrue/phplint/bin/phplint ./ --exclude=vendor
       working-directory: api-php

     - name: Run PHPUnit tests
       run: |
         vendor/phpunit/phpunit/phpunit tests
       working-directory: api-php
